# Autogenerated wrapper script for PhyML_jll for aarch64-linux-gnu-mpi+mpitrampoline
export phyml, phymlMPI

using CompilerSupportLibraries_jll
using MPItrampoline_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("PhyML")
JLLWrappers.@declare_executable_product(phyml)
JLLWrappers.@declare_executable_product(phymlMPI)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        phyml,
        "bin/phyml",
    )

    JLLWrappers.@init_executable_product(
        phymlMPI,
        "bin/phymlMPI",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
