# Autogenerated wrapper script for PhyML_jll for x86_64-w64-mingw32-mpi+microsoftmpi
export phyml, phymlMPI

using CompilerSupportLibraries_jll
using MicrosoftMPI_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("PhyML")
JLLWrappers.@declare_executable_product(phyml)
JLLWrappers.@declare_executable_product(phymlMPI)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        phyml,
        "bin\\phyml.exe",
    )

    JLLWrappers.@init_executable_product(
        phymlMPI,
        "bin\\phymlMPI.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
